# Generated by Django 5.0.4 on 2024-05-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
